---
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection
