#!/usr/bin/env python3
"""Turn hosts/ into OpenTofu inputs.

Each stack under tofu/ is generic: it has no hostnames in it. This script reads
the YAML and writes tofu/<stack>/generated.auto.tfvars.json, which OpenTofu picks
up automatically. The file is gitignored — it is a build artifact, not source.

  scripts/render_tfvars.py --stack hetzner      # every folder of that kind
  scripts/render_tfvars.py --stack pve01        # one Proxmox node
  scripts/render_tfvars.py --stack cloudflare   # DNS for every provider
  scripts/render_tfvars.py --all

Cloudflare needs the public address of every host. Provisioned hosts only have
one after their stack applies, so the pipeline writes build/host_ips.json after
each apply and this script merges it in. Addresses declared in YAML (baremetal,
private networks) are always used as-is.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib import model
from lib.model import Host, ModelError, Repo

TOFU_DIR = model.REPO_ROOT / "tofu"
BUILD_DIR = model.REPO_ROOT / "build"
HOST_IPS_FILE = BUILD_DIR / "host_ips.json"

BANNER = "GENERATED by scripts/render_tfvars.py from hosts/ — do not edit, do not commit."


# Tailscale's direct-connection port. Peers still reach each other without it,
# via a DERP relay, but every packet takes a detour — so a host on the tailnet
# always gets this rule, derived rather than typed into each host file.
TAILSCALE_UDP_PORT = "41641"


def _firewall_rules(host: Host) -> list[dict]:
    rules = [
        {
            "name": r["name"],
            "port": r["port"],
            "protocol": r.get("protocol", "tcp"),
            "source": r.get("source", ["0.0.0.0/0", "::/0"]),
        }
        for r in host.network.get("firewall", [])
    ]
    if host.on_tailnet:
        rules.append(
            {
                "name": "tailscale",
                "port": TAILSCALE_UDP_PORT,
                "protocol": "udp",
                "source": ["0.0.0.0/0", "::/0"],
            }
        )
    if host.public_ssh:
        rules.append(
            {"name": "ssh", "port": "22", "protocol": "tcp", "source": ["0.0.0.0/0", "::/0"]}
        )
    return rules


def host_common(host: Host) -> dict:
    """The provider-independent part of a host, shared by every stack."""
    root = host.root_disk
    return {
        "hostname": host.name,
        "fqdn": host.fqdn,
        "description": host.raw.get("description", ""),
        "cpu": host.hardware["cpu"],
        "memory_mb": host.hardware["memory"],
        "architecture": host.hardware.get("architecture", "x86"),
        "root_disk_gb": root.get("size", 20),
        "extra_disks": [
            {
                "name": d["name"],
                "size_gb": d["size"],
                "type": d.get("type", "ssd"),
                "mount": d.get("mount", f"/mnt/{d['name']}"),
                "format": d.get("format", "ext4"),
            }
            for d in host.extra_disks
        ],
        "image": host.os.get("image") or "",
        "distribution": host.os["distribution"],
        "os_version": host.os["version"],
        "timezone": host.os.get("timezone", "UTC"),
        "ipv4_enabled": host.network.get("ipv4_enabled", True),
        "ipv6_enabled": host.network.get("ipv6_enabled", True),
        "private_ipv4": host.network.get("private_ipv4"),
        "firewall_rules": _firewall_rules(host),
        "ssh_user": host.ansible.get("user", "deploy"),
        "labels": {tag.replace(":", "_"): "true" for tag in host.tags},
        "options": host.raw.get("provider_options", {}) or {},
    }


def render_provider_folder(repo: Repo, provider_name: str) -> dict:
    """One tfvars per provider FOLDER.

    The hcloud and proxmox providers cannot be instantiated dynamically from a
    map, so each folder gets its own OpenTofu workspace and its own var file:

        tofu -chdir=tofu/proxmox workspace select pve01
        tofu -chdir=tofu/proxmox apply -var-file=vars/pve01.tfvars.json

    That keeps pve01's state separate from pve02's, which is what you want when
    one node is down for maintenance.
    """
    provider = repo.providers[provider_name]
    hosts = {h.name: host_common(h) for h in repo.hosts_for_provider(provider_name)}
    return {
        "_banner": BANNER,
        "provider_name": provider_name,
        "credentials": provider.credentials,
        "endpoint": provider.raw.get("endpoint", {}),
        "network": provider.raw.get("network", {}),
        "ssh_keys": provider.ssh_keys,
        "defaults": {
            "location": provider.defaults.get("location"),
            "datastore": provider.defaults.get("datastore"),
            "template": provider.defaults.get("template"),
        },
        "hosts": hosts,
    }


def collect_host_ips(repo: Repo) -> dict[str, dict]:
    """Merge addresses declared in YAML with any the provisioning stacks reported."""
    ips: dict[str, dict] = {}
    for host in repo.hosts.values():
        if not host.enabled:
            continue
        ips[host.name] = {
            "ipv4": host.network.get("ipv4"),
            "ipv6": host.network.get("ipv6"),
            "private_ipv4": host.network.get("private_ipv4"),
        }

    if HOST_IPS_FILE.is_file():
        discovered = json.loads(HOST_IPS_FILE.read_text(encoding="utf-8"))
        for name, values in discovered.items():
            entry = ips.setdefault(name, {})
            for key, value in values.items():
                if value:
                    entry[key] = value
    return ips


def render_cloudflare(repo: Repo) -> dict:
    zones_cfg = repo.zones
    if not zones_cfg:
        return {}
    defaults = zones_cfg.get("defaults", {}) or {}
    prefix = defaults.get("comment_prefix", "managed-by:provision")
    default_ttl = defaults.get("ttl", 1)
    zones = {n: z for n, z in (zones_cfg.get("zones") or {}).items() if z.get("enabled", True)}
    host_ips = collect_host_ips(repo)
    records: dict[str, dict] = {}

    def add(key: str, record: dict) -> None:
        if key in records:
            raise ModelError(f"duplicate Cloudflare record key '{key}'")
        records[key] = record

    # One A/AAAA per host, so `ssh web01.example.com` works and ACME can resolve it.
    for host in repo.hosts.values():
        if not host.enabled:
            continue
        dns = host.dns
        zone = dns.get("zone")
        name = dns.get("record", host.name)
        if not zone or name is None or zone not in zones:
            continue
        proxied = dns.get("proxied", False)
        for record_type, attr in (("A", "ipv4"), ("AAAA", "ipv6")):
            value = (host_ips.get(host.name) or {}).get(attr)
            if not value:
                continue
            add(
                f"host/{host.name}/{record_type}",
                {
                    "zone": zone,
                    "name": name,
                    "type": record_type,
                    "value": value,
                    "ttl": default_ttl,
                    "priority": None,
                    "proxied": proxied,
                    "comment": f"{prefix} host={host.name}",
                },
            )
        for extra in dns.get("extra_records", []) or []:
            extra_zone = extra.get("zone", zone)
            if extra_zone not in zones:
                continue
            add(
                f"host/{host.name}/extra/{extra['type']}/{extra['name']}",
                {
                    "zone": extra_zone,
                    "name": extra["name"],
                    "type": extra["type"],
                    "value": extra["value"],
                    "ttl": extra.get("ttl", default_ttl),
                    "priority": extra.get("priority"),
                    "proxied": extra.get("proxied", False),
                    "comment": extra.get("comment", f"{prefix} host={host.name}"),
                },
            )

    # One record per service domain, pointing at the host that runs it.
    for host in repo.hosts.values():
        if not host.enabled:
            continue
        addresses = host_ips.get(host.name) or {}
        for binding in host.service_bindings:
            for domain in binding.get("domains") or []:
                zone = domain.get("zone")
                if zone not in zones:
                    continue
                record_type = domain.get("record", "A")
                if record_type == "CNAME":
                    value = host.fqdn
                else:
                    value = addresses.get("ipv4" if record_type == "A" else "ipv6")
                if not value:
                    continue
                zone_default = zones[zone].get("default_proxied", defaults.get("proxied", True))
                short = domain["name"]
                if short.endswith("." + zone):
                    short = short[: -(len(zone) + 1)]
                elif short == zone:
                    short = "@"
                add(
                    f"service/{host.name}/{binding['name']}/{domain['name']}/{record_type}",
                    {
                        "zone": zone,
                        "name": short,
                        "type": record_type,
                        "value": value,
                        "ttl": default_ttl,
                        "priority": None,
                        "proxied": domain.get("proxied", zone_default),
                        "comment": f"{prefix} host={host.name} service={binding['name']}",
                    },
                )

    # Zone-level records that belong to nobody in particular (MX, DMARC, ...).
    for zone_name, zone in zones.items():
        for index, record in enumerate(zone.get("records", []) or []):
            add(
                f"zone/{zone_name}/{index}/{record['type']}/{record['name']}",
                {
                    "zone": zone_name,
                    "name": record["name"],
                    "type": record["type"],
                    "value": record["value"],
                    "ttl": record.get("ttl", default_ttl),
                    "priority": record.get("priority"),
                    "proxied": record.get("proxied", False),
                    "comment": record.get("comment", f"{prefix} zone={zone_name}"),
                },
            )

    return {
        "_banner": BANNER,
        "account_id_secret": zones_cfg.get("account_id"),
        "api_token_secret": zones_cfg.get("api_token"),
        "zones": {name: {"zone_id": z["zone_id"]} for name, z in zones.items()},
        "records": records,
    }


PROVISIONING_KINDS = ("hetzner", "proxmox")


def write(target: Path, data: dict, dry_run: bool) -> None:
    payload = json.dumps(data, indent=2, sort_keys=True) + "\n"
    rel = target.relative_to(model.REPO_ROOT)
    if dry_run:
        print(f"--- {rel} ---")
        print(payload)
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(payload, encoding="utf-8")
    count = len(data.get("hosts") or data.get("records") or {})
    print(f"wrote {rel} ({count} entries)")


def render_all(repo: Repo, only: str | None, dry_run: bool) -> None:
    wrote_anything = False

    for name, provider in sorted(repo.providers.items()):
        if provider.kind not in PROVISIONING_KINDS or not provider.enabled:
            continue
        if only and only not in (name, provider.kind):
            continue
        target = TOFU_DIR / provider.kind / "vars" / f"{name}.tfvars.json"
        write(target, render_provider_folder(repo, name), dry_run)
        wrote_anything = True

    if not only or only == "cloudflare":
        data = render_cloudflare(repo)
        if data:
            write(TOFU_DIR / "cloudflare" / "generated.auto.tfvars.json", data, dry_run)
            wrote_anything = True
        else:
            print("cloudflare: no zones configured, skipping")

    if not wrote_anything:
        print("nothing to render")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--stack",
        help="limit to one provider folder (pve01), one kind (proxmox), or 'cloudflare'",
    )
    parser.add_argument("--all", action="store_true", help="render everything")
    parser.add_argument("--dry-run", action="store_true", help="print instead of writing")
    args = parser.parse_args()

    if not args.stack and not args.all:
        parser.error("pass --stack <name> or --all")

    render_all(model.load_repo(), None if args.all else args.stack, args.dry_run)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ModelError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1)
