#!/usr/bin/env python3
"""Build the deploy bundle for a stack on a host.

services/<name>.yml is a plain Compose file with no host-specific anything in it.
This turns it into the exact directory that gets rsynced to /opt/stacks/<name>:

  docker-compose.yml           verbatim copy of services/<name>.yml
  docker-compose.override.yml  generated Traefik labels + edge network attachment
  .env                         non-secret values from the host's binding
  secrets.map                  ENV_VAR=<bitwarden key>, resolved at deploy time
  stack.json                   data dirs, health check, ordering for deploy.sh

Nothing secret is ever written here: secrets.map holds key names only.

  scripts/render_stack.py --host web01 --out build/deploy
  scripts/render_stack.py --host web01 --service gitea --out build/deploy
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import yaml

from lib import model
from lib.model import Host, ModelError, Repo, Service

HEADER = (
    "# GENERATED by scripts/render_stack.py — do not edit on the host.\n"
    "# Source: services/{service}.yml + hosts/{provider}/{host}.yml\n"
)


def order_services(repo: Repo, host: Host, wanted: list[str]) -> list[str]:
    """Depth-first over x-provision.requires so Traefik lands before what it fronts."""
    ordered: list[str] = []
    visiting: set[str] = set()

    def visit(name: str, trail: tuple[str, ...]) -> None:
        if name in ordered:
            return
        if name in visiting:
            raise ModelError("circular requires: " + " -> ".join(trail + (name,)))
        visiting.add(name)
        service = repo.services.get(name)
        if service:
            for dependency in service.requires:
                if repo.binding(host, dependency):
                    visit(dependency, trail + (name,))
        visiting.discard(name)
        ordered.append(name)

    for name in wanted:
        visit(name, ())
    return ordered


def render_override(repo: Repo, host: Host, service: Service) -> dict | None:
    """Labels and network wiring are generated, never hand-written in services/."""
    labels = model.traefik_labels(repo, host, service)
    needs_edge = service.ingress == "traefik"
    if not labels and not needs_edge:
        return None

    target = service.router_service
    override: dict = {"services": {target: {}}}
    if labels:
        override["services"][target]["labels"] = labels
    if needs_edge:
        override["services"][target]["networks"] = ["edge"]
        override["networks"] = {"edge": {"external": True}}
    return override


def env_lines(plain: dict) -> str:
    out = []
    for key in sorted(plain):
        value = str(plain[key])
        # Compose .env does not understand quoting rules the way a shell does;
        # keep values on one line and escape nothing but newlines.
        out.append(f"{key}={value.replace(chr(10), ' ')}")
    return "\n".join(out) + "\n"


def render_one(repo: Repo, host: Host, service: Service, out_root: Path) -> dict:
    binding = repo.binding(host, service.name) or {}
    data_root = binding.get("volumes_root") or f"/srv/{service.name}"
    target = out_root / host.name / service.name
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)

    header = HEADER.format(service=service.name, provider=host.provider.name, host=host.name)

    shutil.copyfile(service.path, target / "docker-compose.yml")
    with (target / "docker-compose.yml").open("r+", encoding="utf-8") as handle:
        body = handle.read()
        handle.seek(0)
        handle.write(header + body)

    override = render_override(repo, host, service)
    if override is not None:
        (target / "docker-compose.override.yml").write_text(
            header + yaml.safe_dump(override, sort_keys=False, default_flow_style=False),
            encoding="utf-8",
        )

    plain, secrets = model.env_for(repo, host, service)
    (target / ".env").write_text(header + env_lines(plain), encoding="utf-8")
    (target / "secrets.map").write_text(
        header + "".join(f"{var}={key}\n" for var, key in sorted(secrets.items())),
        encoding="utf-8",
    )

    manifest = {
        "host": host.name,
        "service": service.name,
        "remote_path": f"/opt/stacks/{service.name}",
        "data_root": data_root,
        "data_dirs": [f"{data_root}/{d}" for d in service.data_dirs],
        "healthcheck_url": service.meta.get("healthcheck_url"),
        "requires": [r for r in service.requires if repo.binding(host, r)],
        "secret_vars": sorted(secrets),
        "domains": [d["name"] for d in binding.get("domains") or []],
        "ssh_user": host.ansible.get("user", "deploy"),
        "ssh_host": host.ansible_host,
        "ssh_port": host.ansible.get("port", 22),
    }
    (target / "stack.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", required=True)
    parser.add_argument("--service", action="append", help="repeatable; default is all of them")
    parser.add_argument("--out", default="build/deploy")
    args = parser.parse_args()

    repo = model.load_repo()
    host = repo.hosts.get(args.host)
    if host is None:
        raise ModelError(f"unknown host '{args.host}'")
    if not host.enabled:
        raise ModelError(f"host '{args.host}' is disabled")

    bound = [b["name"] for b in host.service_bindings]
    wanted = args.service or bound
    for name in wanted:
        if name not in bound:
            raise ModelError(f"host '{host.name}' does not run service '{name}'")

    out_root = Path(args.out)
    if not out_root.is_absolute():
        out_root = model.REPO_ROOT / out_root

    manifests = []
    for name in order_services(repo, host, wanted):
        service = repo.services[name]
        manifests.append(render_one(repo, host, service, out_root))

    plan_path = out_root / host.name / "plan.json"
    plan_path.write_text(json.dumps({"host": host.name, "stacks": manifests}, indent=2) + "\n",
                         encoding="utf-8")
    for manifest in manifests:
        print(f"rendered {host.name}/{manifest['service']} -> {manifest['remote_path']}")
    print(f"plan: {plan_path.relative_to(model.REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ModelError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1)
